USE chess;

CREATE TABLE movement
(
    id     BIGINT AUTO_INCREMENT PRIMARY KEY,
    source VARCHAR(2) NOT NULL,
    target VARCHAR(2) NOT NULL
);

CREATE TABLE chess_board
(
    id     BIGINT AUTO_INCREMENT PRIMARY KEY,
    board   VARCHAR(64) NOT NULL
);

CREATE TABLE turn
(
    id     BIGINT AUTO_INCREMENT PRIMARY KEY,
    team   VARCHAR(5) NOT NULL
);
